---
title: "R Notebook"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

### read in all raw data
```{r, eval=FALSE}
# meta
meta_data = read.csv('./raw/23q4/Model_v2.csv', sep = ",")

dim(meta_data)

head(meta_data)

# mutation
mutation_data = read.csv('./raw/23q4/OmicsSomaticMutationsProfile.csv', sep = ",")


# expression
expr_data = read.csv('./raw/23q4/OmicsExpressionProteinCodingGenesTPMLogp1.csv', sep = ',')

dim(expr_data)
head(expr_data)

# RNAI
load('/Users/liheliu/Projects/SBP/DATA/DepMap/depmap.rda')

# shRNA_dep_scores_convert

# crispr
crispr_data = read.csv('./raw/23q4/CRISPRGeneEffect.csv',sep = ",")
dim(crispr_data)

head(crispr_data)

```


```{r, eval=FALSE}
library(readxl)
AML_cell_names = readxl::read_xlsx('/Users/liheliu/Projects/SBP/LSC17/materials/DepMap_AML_Cell_Lines_Hox_KMT2A_Status_etc.xlsx') %>% 
  # pull(DepMap_ID)
  pull(stripped_cell_line_name)

length(AML_cell_names) # 74 cell lines from Ani file

HOX_gene_names = c(
  names(expr_data)[str_detect(names(expr_data),'HOXA')],
  names(expr_data)[str_detect(names(expr_data),'HOXB')],
  "MEIS2..4212.","MEIS1..4211.",
  "PBX1..5087."
)
# filter out other cancer type, keep only AML
meta_data_aml = meta_data %>%
  dplyr::filter(StrippedCellLineName %in% AML_cell_names) # out of 74, only 53 has data in this verion

## 44 are in the previous heatmap

## 9 extra as the following

# "CMK86"
# "UT7"
# "CESS"
# "KMOE2"   
# "KY821"
# "ML2"
# "NKM1"
# "QIMRWIL"
# "TUR"

# 
expr_data_aml_hox = expr_data %>% 
  dplyr::filter(X %in% (meta_data_aml %>% pull(ModelID))) %>% 
  dplyr::select(X, all_of(HOX_gene_names)) %>%   # # select hox genes (in columns)
  left_join(
    meta_data_aml %>% dplyr::select(ModelID,StrippedCellLineName),
    by = c('X'='ModelID')
  ) %>% 
  # dplyr::select(-X) %>% 
  dplyr::select(StrippedCellLineName, everything()) %>% 
  rename_with(~ sub("\\..*$", "", .x))


## organize data set
gene_names_aml = colnames(expr_data_aml_hox)
cell_names_aml = expr_data_aml_hox$StrippedCellLineName

expr_data_aml_hox_t = t(as.matrix(expr_data_aml_hox))
colnames(expr_data_aml_hox_t) = expr_data_aml_hox_t[1,]
expr_data_aml_hox_t_clean = expr_data_aml_hox_t[-c(1:2),]


expr_data_aml_hox_t_clean_num = matrix(as.numeric(as.vector(expr_data_aml_hox_t_clean)), nrow=nrow(expr_data_aml_hox_t_clean), byrow=TRUE)
colnames(expr_data_aml_hox_t_clean_num) = colnames(expr_data_aml_hox_t_clean)
rownames(expr_data_aml_hox_t_clean_num) = rownames(expr_data_aml_hox_t_clean)


### oder the cell lines
aml_cell_order = c(
  "KO52",
  'KG1',
  'P31FUJ',
  'NOMO1',
  "MONOMAC6",
  'U937',
  "MUTZ3",
  'GDM1',
  "EOL1",
  "MONOMAC1",
  "OCIAML2",
  "MOLM13",
  "MOLM14",
  "HNT34",
  "KASUMI6",
  "OCIAML3",
  "SHI1",
  "OCIAML4",
  "HEL",
  "HEL9217",
  "TF1",
  'MOLM16',
  'OCIM2',
  "OCIM1",
  "ME1",
  "SKM1",
  "OCIAML5",
  "CMK",
  "CMK115",
  "SET2",
  'THP1',
  "KASUMI1",
  "NB4",
  "PLB985",
  'MUTZ8',
  "MV411",
  "M07E",
  "F36P",
  'BDCM',
  "SKNO1",
  "SIGM5",
  "HL60",
  "AML193",
  "PL21"
)

# #
#   "CMK86",
#   "UT7",
#   "CESS",
#   "KMOE2",
#   "KY821",
#   "ML2",
#   "NKM1",
#   "QIMRWIL",
#   "TUR"


aml_gene_order = c(
  'HOXA1',
  'HOXA2',
  'HOXA3',
  'HOXA4',
  'HOXA5',
  'HOXA6',
  'HOXA7',
  'HOXA9',
  'HOXA10',
  'HOXA11',
  'HOXA13',
  'HOXB1',
  'HOXB2',
  'HOXB3',
  'HOXB4',
  'HOXB5',
  'HOXB6',
  'HOXB7',
  'HOXB8',
  'HOXB9',
  'HOXB13',
  "MEIS1",
  "MEIS2",
  "PBX1"
)


# 
# table(aml_cell_order %in% colnames(expr_data_aml_hox_t_clean_num))
# 
# table(aml_gene_order %in% rownames(expr_data_aml_hox_t_clean_num))
# 
expr_data_aml_hox_t_clean_num_ordered = 
  expr_data_aml_hox_t_clean_num[aml_gene_order,aml_cell_order]
# dim(expr_data_aml_hox_t_clean_num)
### heat map

pheatmap(expr_data_aml_hox_t_clean_num_ordered,
         scale = "row",
         clustering_distance_rows = "euclidean", 
         clustering_distance_cols = "euclidean",
         clustering_method = "complete",
         color = colorRampPalette(c("blue", "white", "red"))(255), # Custom color scale: Blue (low) -> White (mid) -> Red (high)
         show_rownames = TRUE, 
         show_colnames = TRUE,
         # clustering_distance_rows = "none", # Do not cluster rows
         cluster_cols = TRUE, # Enable clustering for columns (samples)
         cluster_rows = T, # Set to TRUE if you also want to cluster rows (fea
         main = "Heatmap with Hierarchical Clustering")

# 

```
